name: Build Compass Runtime

on:
  push:
    paths:
      - compass-runtime/**

jobs:
  docker:
    uses: ./.github/workflows/docker-build.yml
    with:
      build_context: compass-runtime
      image_name: fengheai/compass-runtime
      image_tag: dev
    secrets: inherit
